/*
commentId: Unique identifier for each comment
userId: Unique identifier for each user
userName: User's first and last name
message: Message to be saved in the comment
timestamp: Indicator to the exact moment the comment was saved into the database
*/

function createCommentObj(commentId, userId, userName, message, timestamp) {
  return  {
    id: commentId,
    userId: userId,
    userName: userName,
    message: message,
    timestamp: timestamp
  };
}

// Purposely leave out commentId to be pushed into the database because the ID is automatically generated by Firestore which uses it as a key
function createCommentObjForDatabase(userId, userName, message, timestamp) {
  return  {
    userId: userId,
    userName: userName,
    message: message,
    timestamp: timestamp
  };
}

module.exports = { createCommentObj, createCommentObjForDatabase };